services:
  - type: web
    name: sastasmart-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: sastasmart-db
          property: connectionString

databases:
  - name: sastasmart-db
    databaseName: sastasmart
    user: sastasmart
